export const resourceCukcuk = {
    VI: {
        language: 'Tiếng Việt (Tiếng Việt)',
        message: {
            generalErrMsg: 'Đã có lỗi xảy ra, vui lòng liên hệ MISA!',
            codeEmptyMsg: 'Mã không được để trống.',
            nameEmptyMsg: 'Tên không được để trống.',
            departmentEmptyMsg: 'Đơn vị không được để trống.',
            codeErrMsg: 'Mã không đúng định dạng.',
            emailErrMsg: 'Email không đúng định dạng.',
            deleteMultiMsg: 'Bạn có thực sự muốn xóa những nhân viên đã chọn không?',
            changedDataMsg: 'Dữ liệu đã bị thay đổi. Bạn có muốn cất không?',
        },
        expandFunc: {
            replication: 'Nhân bản',
            delete: 'Xóa',
            stopUsing: 'Ngừng sử dụng',
        },
        menuList: {
            menuFood: 'Thực đơn',
        },
        tableHeader: {
            employeeCode: 'MÃ NHÂN VIÊN',
            employeeName: 'TÊN NHÂN VIÊN',
            gender: 'GIỚI TÍNH',
            dateOfBirth: 'NGÀY SINH',
            idNum: 'SỐ CMND',
            idDate: 'NGÀY CẤP',
            idPlace: 'NƠI CẤP',
            position: 'CHỨC DANH',
            departmentCode: 'MÃ ĐƠN VỊ',
            departmentName: 'TÊN ĐƠN VỊ',
            customerSupplier: 'NHÓM KH, NCC',
            receivableAcc: 'TK CÔNG NỢ PHẢI THU',
            payableAcc: 'TK CÔNG NỢ PHẢI TRẢ',
            bankAccNum: 'SỐ TÀI KHOẢN',
            bankName: 'TÊN NGÂN HÀNG',
            phoneNum: 'ĐT DI ĐỘNG',
            landline: 'ĐT CỐ ĐỊNH',
            bankBranch: 'CHI NHÁNH',
            function: 'CHỨC NĂNG',
            noData: 'Không có dữ liệu',
        },
        formLabels: {
            employeeCode: 'Mã',
            employeeName: 'Tên',
            gender: 'Giới tính',
            dateOfBirth: 'Ngày sinh',
            idNum: 'Số CMND',
            idDate: 'Ngày cấp',
            idPlace: 'Nơi cấp',
            position: 'Chức danh',
            department: 'Đơn vị',
            customerSupplier: 'Nhóm khách hàng, nhà cung cấp',
            receivableAcc: 'TK công phải thu',
            payableAcc: 'TK công phải trả',
            address: 'Địa chỉ',
            bankAccNum: 'SỐ TÀI KHOẢN',
            bankName: 'TÊN NGÂN HÀNG',
            phoneNum: 'ĐT di động',
            landline: 'ĐT cố định',
            bankBranch: 'CHI NHÁNH',
            bankCity: 'TỈNH/TP CỦA NGÂN HÀNG',
            employeeInfo: 'Thông tin nhân viên',
            contactTitle: 'Liên hệ',
            bankTitle: 'Tài khoản ngân hàng',
            delete: 'xóa',
            addRow: 'Thêm dòng',
            deleteAllRow: 'Xóa hết dòng'
        },
        others: {
            headerSearch: 'Nhập từ khóa tìm kiếm',
            inputSearch: 'Tìm theo mã, tên nhân viên',
            btnEdit: 'Sửa',
            employee: 'Nhân viên',
            allCategory: 'Tất cả danh mục',
            yes: 'Có',
            no: 'Không',
            cancel: 'Hủy',
            close: 'Đóng',
            agree: 'Đồng ý',
            addNewEmployee: 'Thêm mới nhân viên',
            storeBtn: 'Cất',
            storeAndAddBtn: 'Cất và thêm',
            noFunction: 'Tính năng đang phát triển.'
        }
    },

    EN: {
        language: 'English',
        message: {
            generalErrMsg: 'Something went wrong, please contact MISA for help',
        },

    },
}
